#!/usr/bin/env node
/**
 * Canonical platform statistics pipeline (P0.1).
 *
 * ONE source of truth for every public count. All numbers are DERIVED from the
 * canonical data files — never hand-typed into templates. Running this writes
 * data/platform-stats.json, which platform-stats.js hydrates into any element
 * marked with `data-stat="<key>"`.
 *
 * Canonical concepts are kept distinct (a company-in-a-country listing is NOT a
 * confirmed manufacturing facility; a country office is NOT a factory). Where
 * we do not yet hold evidence for a concept (e.g. confirmed facilities), the
 * count is reported honestly as 0 rather than inferred from listings.
 *
 * Usage:
 *   node scripts/build-stats.js            # write data/platform-stats.json
 *   node scripts/build-stats.js --check    # exit 1 if the file is out of date
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'data', 'platform-stats.json');

const isServedBy = (m) => /^Served by/i.test((m && m[0]) || '');
const clean = (s) => String(s || '').trim();

function loadJson(rel) {
  return JSON.parse(fs.readFileSync(path.join(ROOT, rel), 'utf8'));
}

function computeStats() {
  const manufacturers = loadJson('data/manufacturers.json');
  const utilities = loadJson('data/utility-directory.json');

  const companyNames = new Set();
  const manufacturingCountries = new Set();
  const typeCounts = { PT: 0, DT: 0, DRY: 0, CT: 0 };
  let listings = 0;

  for (const block of manufacturers) {
    const real = (block.makers || []).filter((m) => !isServedBy(m));
    if (real.length > 0) manufacturingCountries.add(clean(block.country));
    for (const m of real) {
      listings++;
      companyNames.add(clean(m[0]));
      const types = clean(m[3])
        .split(',')
        .map((t) => t.trim())
        .filter(Boolean);
      for (const t of types) {
        if (typeCounts[t] === undefined) typeCounts[t] = 0;
        typeCounts[t]++;
      }
    }
  }

  const utilityCount = Array.isArray(utilities)
    ? utilities.length
    : Object.keys(utilities).length;

  return {
    // Distinct manufacturer concepts — deliberately separate.
    manufacturerCompanies: companyNames.size, // distinct legal/operating names
    manufacturerListings: listings, // company-in-country presences (NOT facilities)
    manufacturingCountries: manufacturingCountries.size,
    // Honest: no evidence-backed manufacturing-facility records exist yet.
    manufacturingFacilities: 0,
    transformerTypeListings: typeCounts,
    utilities: utilityCount,
    // Concepts not yet modelled with source data are reported as 0, not inferred.
    componentSuppliers: 0,
    machinerySuppliers: 0,
    laboratories: 0,
    projects: 0,
    tenders: 0,
    openTenders: 0,
    awards: 0,
    events: 0
  };
}

function build() {
  const stats = computeStats();
  const payload = {
    $comment:
      'GENERATED by scripts/build-stats.js — do not edit by hand. Public counts must bind via data-stat.',
    generatedAt: new Date().toISOString(),
    source: 'data/manufacturers.json, data/utility-directory.json',
    stats
  };
  return payload;
}

function stableStats(obj) {
  // Compare only the stats (ignore generatedAt) so --check is deterministic.
  return JSON.stringify((obj && obj.stats) || obj);
}

if (require.main === module) {
  const payload = build();
  if (process.argv.includes('--check')) {
    let existing = null;
    try {
      existing = JSON.parse(fs.readFileSync(OUT, 'utf8'));
    } catch (e) {
      console.error('platform-stats.json missing or unreadable — run: node scripts/build-stats.js');
      process.exit(1);
    }
    if (stableStats(existing) !== stableStats(payload)) {
      console.error('platform-stats.json is STALE. Re-run: node scripts/build-stats.js');
      console.error('  on disk:  ' + stableStats(existing));
      console.error('  computed: ' + stableStats(payload));
      process.exit(1);
    }
    console.log('platform-stats.json is up to date.');
    process.exit(0);
  }
  fs.writeFileSync(OUT, JSON.stringify(payload, null, 2) + '\n');
  console.log('Wrote ' + path.relative(ROOT, OUT));
  console.log(JSON.stringify(payload.stats, null, 2));
}

module.exports = { computeStats, build };
