/**
 * Canonical platform-stats hydrator (P0.1).
 *
 * Any element marked with data-stat="<key>" is filled from the single source of
 * truth, data/platform-stats.json (generated by scripts/build-stats.js). The
 * element's existing text is a build-time fallback for no-JS / pre-hydration
 * rendering and is verified against the canonical value by the build gate
 * (scripts/check-stats.js), so it can never silently drift.
 *
 * Keys: manufacturerCompanies, manufacturerListings, manufacturingCountries,
 * manufacturingFacilities, utilities, componentSuppliers, machinerySuppliers,
 * laboratories, projects, tenders, openTenders, awards, events.
 */
(function () {
  var STATS_URL = 'data/platform-stats.json';

  function format(value, mode) {
    if (typeof value !== 'number') return value;
    if (mode === 'plain') return String(value);
    return value.toLocaleString('en-US');
  }

  function apply(stats) {
    var nodes = document.querySelectorAll('[data-stat]');
    Array.prototype.forEach.call(nodes, function (el) {
      var key = el.getAttribute('data-stat');
      if (!key || !(key in stats)) return;
      var mode = el.getAttribute('data-stat-format') || 'comma';
      el.textContent = format(stats[key], mode);
      el.setAttribute('data-stat-hydrated', 'true');
    });
    // Expose for other scripts that want canonical numbers.
    window.TP_PLATFORM_STATS = stats;
    document.dispatchEvent(new CustomEvent('tp:stats', { detail: stats }));
  }

  function init() {
    fetch(STATS_URL, { cache: 'no-cache' })
      .then(function (res) {
        if (!res.ok) throw new Error('HTTP ' + res.status);
        return res.json();
      })
      .then(function (json) {
        apply((json && json.stats) || json || {});
      })
      .catch(function (err) {
        // Leave build-time fallback text in place; never blank a count.
        console.warn('platform-stats: using fallback text (' + err.message + ')');
      });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
